In [1]:
import numpy as np
import pandas as pd
scroes = np.random.randint(50, 100,size=(50,5))
scores_df = pd.DataFrame(scroes,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores_df
sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values

In [2]:
scores_df
scores_df.style.highlight_between(left=50,right=59)

In [3]:
scores_df
scores_df.style\
    .format(precision=3)\
    .highlight_between(left=50,right=59)\
    .to_excel('abc.xlsx')

In [4]:
scores_df
scores_df.style\
    .format(precision=2)\
    .highlight_between(left=50,right=59,props='color:white; background-color:#CB1B45;')\
    .highlight_max(axis=1,subset=scores_df.columns[:5],props='color:white; background-color:#2B5F75;')\

In [ ]:
#未完待續 老師下一堂解答（題目：一一個欄位篩選，一次產生多個檔案）
from openpyxl import load_workbook
book = load_workbook('天龍國小.xlsx')
writer = pd.ExcelWriter('天龍國小.xlsx',engine='openpyxl')
writer.book = book
writer.sheets = dict((ws.title,ws)for ws in book.worksheets)
pdstyle.to_excel(writer,sheet_name='3年2班')